[package]
name = "tzfile-to-json"
version = "0.1.0"
authors = ["Nicolas BAUW <nicolas.bauw@leroymerlin.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
chrono = "0.4"