[package]
name = "libtzfile"
version = "0.4.0"
authors = ["Nicolas BAUW <nbauw@hotmail.com>"]
description = "A low-level library to read timezone information files."
keywords = ["timezone", "tzfiles", "TZIF"]
categories = ["date-and-time", "parsing"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/nicolasbauw/rs-tzfile"
exclude = [
    "file_structure.txt"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
chrono = { version = "0.4", optional = true }
dirs = "2.0.2"

[features]
with-chrono = ["chrono"]